version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:5.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: success_project
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
